spring.application.name=LeadManagementApplication

server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://13.201.29.113/aman?createDatabaseIfNotExist=true
spring.datasource.username=aman
spring.datasource.password=jrBKtrLSAkieKArC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=amlearning12@gmail.com
spring.mail.password=ifir cvxv uydk wbqq

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.base-url=https://lead-management-backend.onrender.com
